---
AWSTemplateFormatVersion: '2010-09-09'
Description: Auth - sign in, up and out

Parameters:
  StackName:
    Description: Auth for retail users and normal users
    Type: String
    Default: cognito-stack
  Stage:
    Type: String

Resources:
  #Retail userpool, users in the retail-webapp
  RetailCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration: 
        CaseSensitive: False
      AutoVerifiedAttributes:
        - email
      UserPoolName: Retail Pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: False
          Required: True
        - Name: name
          AttributeDataType: String
          Mutable: True
          Required: True
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AutoVerifiedAttributes: 
        - email
      DeviceConfiguration: 
        ChallengeRequiredOnNewDevice: True
      EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          SourceArn:  arn:aws:ses:us-east-1:117468630787:identity/team@biteapp.co.nz #verified arn of sns email
          ReplyToEmailAddress: team@biteapp.co.nz
      EmailVerificationMessage: Welcome to bite! Please confirm your email address {####}
      EmailVerificationSubject: Bite Account Verification
      AdminCreateUserConfig:
          AllowAdminCreateUserOnly: True
      UsernameAttributes: 
        - email

  RetailCognitoPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref RetailCognitoPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://biteapp.work/oauth2/idpresponse

      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 2
      RefreshTokenValidity: 24
      IdTokenValidity: 2
      TokenValidityUnits: 
          AccessToken: hours
          IdToken: hours
          RefreshToken: hours
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH

      PreventUserExistenceErrors: ENABLED
      GenerateSecret: true
  
  RetailCognitoPoolClientNoSecret:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref RetailCognitoPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://biteapp.work/oauth2/idpresponse

      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 2
      RefreshTokenValidity: 24
      IdTokenValidity: 2
      TokenValidityUnits: 
          AccessToken: hours
          IdToken: hours
          RefreshToken: hours
      AllowedOAuthFlowsUserPoolClient: true
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH       
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  RetailCognitoPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: bite-retail-auth
      UserPoolId: !Ref RetailCognitoPool

  #User userpool, users in the android and ios app
  UserCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration: 
        CaseSensitive: False
      AutoVerifiedAttributes:
        - email
      UserPoolName: User Pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: False
          Required: True
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AutoVerifiedAttributes: 
        - email
      DeviceConfiguration: 
        ChallengeRequiredOnNewDevice: True
      EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          SourceArn:  arn:aws:ses:us-east-1:117468630787:identity/team@biteapp.co.nz #verified arn of sns email
          ReplyToEmailAddress: team@biteapp.co.nz
      EmailVerificationMessage: Welcome to bite! Please confirm your email address {####}
      EmailVerificationSubject: Bite Account Verification
      UsernameAttributes: 
        - email
      UserNameConfiguration:
          CaseSensitive: False


  UserCognitoPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserCognitoPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://biteapp.work/oauth2/idpresponse

      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 2
      RefreshTokenValidity: 24
      IdTokenValidity: 2
      TokenValidityUnits: 
          AccessToken: hours
          IdToken: hours
          RefreshToken: hours
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

      PreventUserExistenceErrors: ENABLED
      GenerateSecret: true

  UserCognitoPoolClientNoSecret:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserCognitoPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - https://biteapp.work/oauth2/idpresponse
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      AccessTokenValidity: 2
      RefreshTokenValidity: 24
      IdTokenValidity: 2
      TokenValidityUnits: 
          AccessToken: hours
          IdToken: hours
          RefreshToken: hours
      ExplicitAuthFlows: 
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  UserCognitoPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: bite-user-auth
      UserPoolId: !Ref UserCognitoPool